### ISSUE TITLE
Problema para rodar a remoção.

### ISSUE THREAD

**Issue by pcb97** [heliocamargo/remocaovies_ECMWF_ENSExtended#2]
Olá heliocamargo. 
Estou com problema para rodar a remoção com os arquivos fornecidos pela ONS. 
Tenho obtido o erro "Use only with 'fitdist' objects" em alguns decks e o erro "Non-numeric argument to mathematical function" em outros decks. Estou usando o deck puro disponibilizado pela ONS, sem nenhuma modificação.
Tem algum motivo para esses erros estarem acontecendo?
Poderia me mandar as configurações/versões de bibliotecas, R e sistema operacional que você usa ?
Obrigado!

**Comment by tok-yuri** [comment]
@pcb97 em que parte do código aparecem esses erros, quais decks vc viu isso e quais são as configurações que você está utilizando para rodar (OS, versão do R ou conda e como está fazendo a instalação das bibliotecas).
Aqui eu utilizo linux e tive que fazer alguns ajustes no código para rodar com menos incompatibilidade de nomes.

**Comment by pcb97** [comment]
@tok-yuri  Os erros relacionados ao fitdist estão ocorrendo no arquivo: gammarize_function.R na linha 163 do commit mais recente. Estou rodando em paralelo e o erro ocorre apenas em algumas threads.
Esse erro está acontecendo em todos os decks disponibilizados pela ONS nas ultimas duas semanas.
Estou rodando com docker em uma EC2 na AWS usando a imagem para R "rocker/r-base:4.2.3" mas já tentei com a "rocker/r-base:4.4.2" e da o mesmo erro.
Estou instalando as bibliotecas usando o "install.packages(c(''')), repos='http://cran-r.c3sl.ufpr.br/')" no R.
Vale ressaltar que são apenas algumas threads que não rodam, a maioria roda normalmente e que esse problema não ocorria a algumas semanas atrás.
Print do erro: "Error in { : task 47 failed - "Use only with 'fitdist' objects""

**Comment by tok-yuri** [comment]
@pcb97 Eu utilizo um docker miniconda, então podemos não ter o mesmo problema. Mas algo parecido aconteceu comigo causado por não respeitar o fato de deixar pelo menos 1 core livre e por limitação de memória.
Talvez é uma boa ver no log da máquina a utilização da memória e do processamento.
Nos meus testes, acima de 95% da memória da máquina já é possível dar algum problema na rodada.

**Comment by pcb97** [comment]
@tok-yuri Tenho deixado 1 core e memoria Ram livre para o sistema.
Mas então os decks das ultimas semanas tem rodado normalmente com você né? Achei que poderia ser algo com o Deck da ONS, mas então deve ser algo com minha configuração.
